name: Test & Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO111MODULE: on
  # For versions earlier than Go 1.13
  GOPROXY: https://proxy.golang.org

jobs:
  test_and_build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.13.x, 1.12.x, 1.11.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set GOPATH and PATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}

    - name: Install dependencies
      run: go get -v golang.org/x/lint/golint

    - name: Build
      run: go build
    
    - name: Lint
      run: golint -set_exit_status ./...

    - name: Test
      run: go test -race --coverprofile=coverage.txt --covermode=atomic ./...

    - name: Upload coverage to Codecov
      if: success() && matrix.go-version == '1.14.x' && matrix.platform == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false